[id]
version = 0.0.1

[install]
is_configured = 0

[ui]
is_visible = 1
label = DNS Parse

[launcher]
author = TerminalOutcomes
description = Parse base64 DNS wire responses in search results
version = 0.0.1

[package]
check_for_updates = true